project:
  type: website
  output-dir: docs

website:
  title: "Basir Talayee"
  navbar:
    left:
      - about.qmd
      - activities.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    

editor: visual

